import React from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import GlobalStyles from '@/components/GlobalStyles/GlobalStyles';
import Providers from '@/components/Providers/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <GlobalStyles />
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}

export default RootLayout;
